"""
Comparison script to test numpy (HypotheticalInputsForNN) vs TensorFlow
(PointsToInputsConstStep) implementations.

Largely generated by Claude Code, though I rewrote parts to use my posemath
library, load the column order via pickle, etc.

The tolerance also seems too picky, and right now the test assumes we won't
see very fast rotations. Because axis-angle representations of angular
displacement are not unique, all angular displacements are assumed to be < pi in
magnitude when in fact an object might be spinning really fast... but *probably*
not in most of our AR use cases.
"""
import pickle

import numpy as np
import tensorflow as tf


# tf.config.run_functions_eagerly(True)

from motiontools.hypothetical_inputs_calc import HypotheticalInputsForNN
from motiontools.dataorg import UnitAwareScaler
from nn_utilities.nn_inference import PointsToInputsConstStep

import posemath as pm

def generate_test_data(step=1, n_points=5):
    """Generate random test data for comparison."""
    
    # If we assume a "skip" of 2 frames each time, this will ensure that our
    # largest between-samples rotation is less than pi radians. Is this
    # realistic? Currently, if our video is 30fps, meaning our "skip" video
    # is 10fps, this would still allow rotations of over 2 revolutions per
    # second, which seems rare enough to ignore for now. 
    pi_o_4 = np.pi/4.0

    random_first_mats = [pm.randomRotationMat() for _ in range(n_points)]
    random_ang_vel_dirs = pm.normalizeAll(np.random.randn(5, n_points, 3))
    random_ang_vel_mags = np.random.uniform(0, pi_o_4, (5, n_points, 1))
    random_ang_vels = random_ang_vel_mags * random_ang_vel_dirs
    rvel_mats = pm.matsFromScaledAxisAngleArray(random_ang_vels)
    
    all_mats = [random_first_mats]
    for i in range(5):
        next_mats = pm.einsumMatMatMul(all_mats[-1], rvel_mats[i])
        all_mats.append(next_mats)

    rmats0_through_5 = np.stack(all_mats, axis=0)
    random_axis_angles = pm.axisAngleFromMatArray(rmats0_through_5)

    # Generate random positions (5 points for x0_through_4)
    x0_through_4 = np.random.randn(5, n_points, 3) * 10
    # Generate test point (x5) - the next point to predict from
    x5 = np.random.randn(n_points, 3) * 10
    
    # Create full sequence including x5 for TensorFlow version
    x0_through_5 = np.concatenate([x0_through_4, x5[np.newaxis, :, :]], axis=0)
    
    # Convert all returned numpy arrays to np.float32:
    x0_through_4 = x0_through_4.astype(np.float32)
    x5 = x5.astype(np.float32)
    x0_through_5 = x0_through_5.astype(np.float32)
    rmats0_through_5 = rmats0_through_5.astype(np.float32)
    random_axis_angles = random_axis_angles.astype(np.float32)

    return x0_through_4, rmats0_through_5, x5, x0_through_5, random_axis_angles


def compare_implementations(step=1, n_points=5, tolerance=1e-4):
    """Compare numpy and TensorFlow implementations."""
    
    print(f"Testing with step={step}, n_points={n_points}")
    print("=" * 70)
    
    # Generate test data
    x0_through_4, rmats0_through_5, x5, x0_through_5, axis_angles = generate_test_data(step, n_points)
    
    scaler: UnitAwareScaler
    with open("./results/models/scaler.pickle", "rb") as f:
        scaler = pickle.load(f)
    
    # Initialize numpy version
    numpy_calcer = HypotheticalInputsForNN(
        x0_through_4, rmats0_through_5, step, scaler.column_keys
    )
    
    # Calculate numpy results
    print("Computing numpy results...")
    numpy_results, numpy_jav, numpy_ortho = numpy_calcer.getHypotheticalCalcs(x5)
    print(f"Numpy output shape: {numpy_results.shape}")
    print(f"Numpy JAV shape: {numpy_jav.shape}")
    print(f"Numpy ortho shape: {numpy_ortho.shape}")
    
    # Initialize TensorFlow version
    print("\nComputing TensorFlow results...")
    tf_calcer = PointsToInputsConstStep(step, scaler.column_keys)
    
    # Convert inputs to TensorFlow tensors
    x0_through_5_tf = tf.constant(x0_through_5, dtype=tf.float32)
    axis_angles_tf = tf.constant(axis_angles, dtype=tf.float32)
    
    # Calculate TensorFlow results
    tf_results = tf_calcer.calculateOutputs(x0_through_5_tf, axis_angles_tf)
    tf_results_np = tf_results.numpy()
    
    print(f"TensorFlow output shape: {tf_results_np.shape}")
    
    # Compare results
    print("\n" + "=" * 70)
    print("COMPARISON RESULTS")
    print("=" * 70)
    
    # Check if shapes match
    if numpy_results.shape == tf_results_np.shape:
        print("✓ Shapes match!")
    else:
        print(f"✗ Shape mismatch: numpy {numpy_results.shape} vs TF {tf_results_np.shape}")
        return False
    
    # Calculate differences
    abs_diff = np.abs(numpy_results - tf_results_np)
    max_abs_diff = np.max(abs_diff)
    mean_abs_diff = np.mean(abs_diff)
    
    # Calculate relative differences (where numpy result is non-zero)
    numpy_nonzero = np.abs(numpy_results) > 1e-10
    rel_diff = np.zeros_like(abs_diff)
    if np.any(numpy_nonzero):
        rel_diff[numpy_nonzero] = abs_diff[numpy_nonzero] / np.abs(numpy_results[numpy_nonzero])
        max_rel_diff = np.max(rel_diff[numpy_nonzero])
        mean_rel_diff = np.mean(rel_diff[numpy_nonzero])
    else:
        max_rel_diff = 0.0
        mean_rel_diff = 0.0
    
    print(f"\nAbsolute differences:")
    print(f"  Max:  {max_abs_diff:.2e}")
    print(f"  Mean: {mean_abs_diff:.2e}")
    
    print(f"\nRelative differences (where numpy != 0):")
    print(f"  Max:  {max_rel_diff:.2e}")
    print(f"  Mean: {mean_rel_diff:.2e}")
    
    # Check tolerance
    if max_rel_diff < tolerance:
        print(f"\n✓ Results match within tolerance ({tolerance:.2e})!")
        success = True
    else:
        print(f"\n✗ Results differ beyond tolerance ({tolerance:.2e})")
        
        # Find indices where differences are largest
        max_rel_diff_per_col = np.max(rel_diff, axis=0)
        
        offending_cols = np.nonzero(max_rel_diff_per_col >= tolerance)[0]
        
        n_keys = len(scaler.column_keys)
        print(f"\nOffending columns ({len(offending_cols)}/{n_keys}):")
        for oc in offending_cols:
            print(f" - {oc} ({scaler.column_keys[oc].name}): {max_rel_diff_per_col[oc]}")
        
        # print("\nShowing first few mismatches:")
        # sorted_indices = np.argsort(max_rel_diff_per_col)
        # for idx in sorted_indices[-5:]:
        #     row, col = np.unravel_index(idx, abs_diff.shape)
        #     print(f"  [{row:3d}, {col:3d}]: numpy={numpy_results[row, col]:12.6e}, "
        #           f"tf={tf_results_np[row, col]:12.6e}, diff={abs_diff[row, col]:12.6e}, "
        #           f"name={ref_keys[col].name}"
        #     )
        # print("\nMeanwhile, the closest matches:")
        # for idx in sorted_indices[:5]:
        #     row, col = np.unravel_index(idx, abs_diff.shape)
        #     print(f"  [{row:3d}, {col:3d}]: numpy={numpy_results[row, col]:12.6e}, "
        #             f"tf={tf_results_np[row, col]:12.6e}, diff={abs_diff[row, col]:12.6e}, "
        #             f"name={ref_keys[col].name}"
        #     )
        success = False
    
    # Show sample values for debugging
    print("\n" + "=" * 70)
    print("SAMPLE VALUES (first point, first 10 columns)")
    print("=" * 70)
    print("Column | Numpy Value      | TF Value         | Difference")
    print("-" * 70)
    for i in range(min(10, numpy_results.shape[1])):
        numpy_val = numpy_results[0, i]
        tf_val = tf_results_np[0, i]
        diff = abs(numpy_val - tf_val)
        print(f"{i:6d} | {numpy_val:15.8e} | {tf_val:15.8e} | {diff:12.6e}")
    
    return success


def main():
    """Run comparison tests with different configurations."""
    
    print("Comparing NumPy and TensorFlow implementations")
    print("=" * 70)
    print()
    
    test_configs = [
        {"step": 1, "n_points": 5},
        {"step": 2, "n_points": 10},
        {"step": 1, "n_points": 1},  # Single point test
    ]
    
    all_passed = True
    
    for config in test_configs:
        try:
            passed = compare_implementations(**config)
            all_passed = all_passed and passed
            print("\n" * 2)
        except Exception as e:
            print(f"\n✗ Test failed with error: {e}")
            import traceback
            traceback.print_exc()
            all_passed = False
            print("\n" * 2)
    
    print("=" * 70)
    if all_passed:
        print("✓ All tests passed!")
    else:
        print("✗ Some tests failed")
    print("=" * 70)


if __name__ == "__main__":
    main()
