"""
Test suite for posemath.safelyNormalizeArray function.
This was auto-generated by Claude Code based on an very informal version that
I've included in a comment at the bottom of this file.
Future tests should be a bit more thorough testing the various parameters, such
as choice of propagation axis and propagating vectors backwards if the first
vector is zero (meaning forward propagation does not work in this case).
"""
import unittest
import numpy as np
import posemath as pm


class TestSafelyNormalizeArray(unittest.TestCase):
    """Test cases for safelyNormalizeArray function."""

    def test_simple_normalization_nonzero_vector(self):
        """Test normalization of a simple non-zero vector."""
        input_vec = np.asarray([1, 0, 1])
        result = pm.safelyNormalizeArray(
            input_vec,
            vec_for_zero_norms=np.zeros(3),
            propagate_back_if_first_vecs_zero=True,
            propagation_axis=100
        )
        expected_norm = np.linalg.norm(input_vec)
        expected = input_vec / expected_norm
        np.testing.assert_allclose(result, expected)
        # Verify result is normalized
        np.testing.assert_allclose(np.linalg.norm(result), 1.0)

    def test_zero_vector_with_zero_replacement(self):
        """Test that a zero vector with zero replacement returns zeros."""
        input_vec = np.zeros(3)
        result = pm.safelyNormalizeArray(
            input_vec,
            vec_for_zero_norms=np.zeros(3),
            propagate_back_if_first_vecs_zero=True,
            propagation_axis=100
        )
        np.testing.assert_array_equal(result, np.zeros(3))

    def test_zero_vector_with_unit_vector_replacement(self):
        """Test that a zero vector with unit vector replacement works correctly."""
        input_vec = np.zeros(3)
        unit_vec = np.array([1.0, 0.0, 0.0])  # Unit vector
        result = pm.safelyNormalizeArray(
            input_vec,
            vec_for_zero_norms=unit_vec,
            propagate_back_if_first_vecs_zero=True,
            propagation_axis=100
        )
        np.testing.assert_array_equal(result, unit_vec)

    def test_multidimensional_with_scattered_zeros(self):
        """Test normalization of multi-dimensional array with scattered zero vectors."""
        # Create test data with known structure
        np.random.seed(42)  # For reproducibility
        x = np.random.uniform(-1, 1, (4, 5, 3))
        
        # Set specific locations to zero
        x[0, 0] = 0
        x[0, 3] = 0
        x[1, :, 0] = 0
        x[2, :2] = 0
        x[3, 1:3] = 0
        
        xn = np.linalg.norm(x, axis=-1, keepdims=True)
        result = pm.safelyNormalizeArray(
            x, xn,
            vec_for_zero_norms=None,
            propagate_back_if_first_vecs_zero=False,
            propagation_axis=0
        )
        
        # Verify that non-zero vectors are normalized
        non_zero_mask = xn[..., 0] > 1e-10
        result_norms = np.linalg.norm(result[non_zero_mask], axis=-1)
        np.testing.assert_allclose(result_norms, 1.0, rtol=1e-6)
        
        # Verify that normalized vectors are parallel to original vectors
        # (cross product should be zero)
        flatter_x = x.reshape(-1, 3)
        flatter_r = result.reshape(-1, 3)
        cross_result = np.cross(flatter_x, flatter_r).reshape(x.shape)
        np.testing.assert_allclose(cross_result, 0, atol=1e-10)

    def test_propagation_preserves_direction(self):
        """Test that vector propagation maintains proper direction."""
        # Create a sequence with a zero vector after a non-zero vector
        x = np.array([
            [[1.0, 0.0, 0.0]],
            [[0.0, 0.0, 0.0]],
            [[0.0, 1.0, 0.0]]
        ])
        
        result = pm.safelyNormalizeArray(
            x,
            vec_for_zero_norms=None,
            propagate_back_if_first_vecs_zero=False,
            propagation_axis=0
        )
        
        # The zero vector at index 1 should be replaced with the vector from index 0
        np.testing.assert_array_equal(result[0, 0], [1.0, 0.0, 0.0])
        np.testing.assert_array_equal(result[1, 0], [1.0, 0.0, 0.0])  # Propagated
        np.testing.assert_array_equal(result[2, 0], [0.0, 1.0, 0.0])

    def test_no_zeros_simple_normalization(self):
        """Test that arrays without zero vectors are normalized correctly."""
        x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        result = pm.safelyNormalizeArray(x, vec_for_zero_norms=None)
        
        # Check each vector is normalized
        for i in range(len(x)):
            expected = x[i] / np.linalg.norm(x[i])
            np.testing.assert_allclose(result[i], expected)
            np.testing.assert_allclose(np.linalg.norm(result[i]), 1.0)

    def test_precomputed_norms(self):
        """Test that providing precomputed norms works correctly."""
        x = np.array([[3.0, 4.0, 0.0], [1.0, 0.0, 0.0]])
        norms = np.linalg.norm(x, axis=-1, keepdims=True)
        
        result = pm.safelyNormalizeArray(
            x, norms=norms,
            vec_for_zero_norms=None,
            propagate_last_nonzero_vec=False
        )
        
        # Verify normalization
        for i in range(len(x)):
            expected = x[i] / norms[i, 0]
            np.testing.assert_allclose(result[i], expected)

    def test_all_zero_vectors_with_replacement(self):
        """Test handling of an array where all vectors are zero."""
        x = np.zeros((3, 3))
        replacement = np.array([1.0, 0.0, 0.0])
        
        result = pm.safelyNormalizeArray(
            x,
            vec_for_zero_norms=replacement,
            propagate_last_nonzero_vec=False
        )
        
        # All vectors should be replaced with the replacement vector
        for i in range(len(x)):
            np.testing.assert_array_equal(result[i], replacement)

    def test_invalid_replacement_vector_raises_error(self):
        """Test that non-unit, non-zero replacement vectors raise ValueError."""
        input_vec = np.zeros(3)
        invalid_vec = np.array([1.0, 1.0, 1.0])  # Not unit, not zero (norm = sqrt(3))
        
        with self.assertRaises(ValueError) as context:
            pm.safelyNormalizeArray(
                input_vec,
                vec_for_zero_norms=invalid_vec,
                propagate_last_nonzero_vec=False
            )
        
        self.assertIn("must be either a zero vector or a unit vector", str(context.exception))

    def test_valid_replacement_vectors_accepted(self):
        """Test that both zero and unit vectors are accepted as replacements."""
        input_vec = np.zeros(3)
        
        # Zero vector should be accepted
        result1 = pm.safelyNormalizeArray(
            input_vec.copy(),
            vec_for_zero_norms=np.zeros(3),
            propagate_last_nonzero_vec=False
        )
        np.testing.assert_array_equal(result1, np.zeros(3))
        
        # Unit vector should be accepted
        unit_vec = np.array([0.0, 1.0, 0.0])
        result2 = pm.safelyNormalizeArray(
            input_vec.copy(),
            vec_for_zero_norms=unit_vec,
            propagate_last_nonzero_vec=False
        )
        np.testing.assert_array_equal(result2, unit_vec)


if __name__ == '__main__':
    unittest.main()

"""
Original "tests" used to generate this file:
    # %%
    import numpy as np
    import posemath as pm
    
    # %%
    pm.safelyNormalizeArray(np.asarray([1, 0, 1]), vec_for_zero_norms=np.zeros(3), propagate_back_if_first_vecs_zero=True, propagation_axis=100)
    
    # %%
    pm.safelyNormalizeArray(np.zeros(3), vec_for_zero_norms=np.zeros(3), propagate_back_if_first_vecs_zero=True, propagation_axis=100)
    
    # %%
    pm.safelyNormalizeArray(np.zeros(3), vec_for_zero_norms=np.ones(3), propagate_back_if_first_vecs_zero=True, propagation_axis=100)
    
    # %%
    
    x = np.random.uniform(-1, 1, (4, 5, 3))
    xo = x.copy()
    
    x[0, 0] = 0
    x[0, 3] = 0
    x[1, :, 0] = 0
    x[2, :2] = 0
    x[3, 1:3] = 0
    
    xo2 = x.copy()
    
    # %%
    print(xo)
    
    # %%
    print(x)
    
    # %%
    x = xo2.copy()
    xn = np.linalg.norm(x, axis=-1, keepdims=True)
    r = pm.safelyNormalizeArray(
        x, xn,
        vec_for_zero_norms=None,
        propagate_back_if_first_vecs_zero=False,
        propagation_axis=0
    )
    # r = pm.safelyNormalizeArray(
    #     x, xn, vec_for_zero_norms=np.zeros(3),
    #     propagate_last_nonzero_vec=False
    # )
    
    flatter_x = x.reshape(-1, 3)
    flatter_r = r.reshape(-1, 3)
    cross_result = np.linalg.cross(flatter_x, flatter_r).reshape(x.shape)
    
    print(r)
    print("Cross okay:", np.allclose(cross_result, 0))
    
    #%%
    print(cross_result)
"""
