"""
Caching utilities for expensive DataForJAV computations.
Saves large NDArrays to disk and loads them on subsequent runs.

This code was initially generated by Claude Sonnet 4.5 and Cline in an attempt
to see whether they would be able to automate a task. They were able to perform
part of it but I've given up and will be finishing the rest solo. I will also
probably forget to update this comment after doing so.
"""
import hashlib
import json
import typing
from pathlib import Path
import enum

import numpy as np
from numpy.typing import NDArray, ArrayLike

from datatools.data_splitting import DataSubsetKind
from nn_utilities.nn_modes import OutVecMode

CACHE_DATA_LOCATION = "generated_data"

class CacheKeys(enum.Enum):
    PREV_VEL_AX_KEY = "prev_vel_axes"
    PREV_ANG_KEY = "prev_vel_angs"
    GT_ROT_VELS_KEY = "gt_rot_vels"

    W2L_MATS_KEY = "w2l_mats"

    JAV_12 = "jav_12_vals"

    EXTRA_ROT_ALIGN_COLS_KEY = "_extra_rot_align_cols"
    EXTRA_NO_ROT_ALIGN_COLS_KEY = "_extra_no_rot_align_cols"

    GT_STORAGE_KEY = "gt_for_outvecmode"
    POS_SCALE_KEY = "pos_scale"
    ROT_SCALE_KEY = "rot_scale"
    VALIDATION_START_IND_KEY = "validation_start_ind"
    TEST_START_IND_KEY = "test_start_ind"


def gen_cache_key(
    dataset_name: str, data_ids: typing.Dict[DataSubsetKind, typing.List],
    max_ids_per_hash: typing.Optional[int] = None
) -> str:
    """
    Generate a unique cache key based on parameters that affect the computation.
    
    Parameters:
        dataset_name (str): Name of dataset the IDs are for
        data_ids: Dictionary mapping subset kinds to lists of data IDs
        max_ids_per_hash (int): Maximum number of IDs per DataSubsetKind to use 
            for hash calculations (default: None)
    Returns:
        A string that uniquely identifies this configuration
    """
    # Create a dictionary of all parameters that affect computation
    partial_hashes = {
        _dsk.name: hashlib.sha256(",".join(
            [repr(tuple(x)) for x in ids[:max_ids_per_hash]]
        ).encode('utf-8')).hexdigest()
        for _dsk, ids in data_ids.items()
    }
    id_lens = {}
    if max_ids_per_hash is not None:
        id_lens = {_dsk: len(ids) for _dsk, ids in data_ids.items()}
    cache_params = {**partial_hashes, **id_lens}
    
    # Convert to JSON string for hashing (sorted for consistency)
    params_str = json.dumps(cache_params, sort_keys=True)
    
    # Generate hash
    hash_obj = hashlib.sha256(params_str.encode('utf-8'))
    return dataset_name + "_" + hash_obj.hexdigest()[:16]  # 16 for brevity


def get_cache_filepath(cache_key: str, cache_dir: str = CACHE_DATA_LOCATION) -> Path:
    """Get the filepath for a cache file."""
    cache_path = Path(cache_dir)
    cache_path.mkdir(exist_ok=True)
    return cache_path / f"data_cache_{cache_key}.npz"


def save_cached_data(
    cache_key: str, data_to_cache: typing.Dict[str, NDArray],
    gt_to_cache: typing.Dict[OutVecMode, NDArray],
    validation_start_ind: int, test_start_ind: int,
    pos_scale: float, rot_scale: float, cache_dir: str = CACHE_DATA_LOCATION
) -> None:
    """
    Save expensive computed arrays to disk.
    
    Parameters:
        cache_key (str): Unique identifier for this cache
        data_to_cache (dict[str, NDArray]): Dictionary containing various data to cache
        gt_to_cache (dict[OutVecMode, NDArray]): Dictionary containing all ground truth data to cache
        validation_start_ind (int): Index where validation data starts in the dataset
        test_start_ind (int): Index where test data starts in the dataset
        pos_scale (float): Scaling used for translations
        rot_scale (float): Scaling used for rotations
        cache_dir (str, optional): Directory to save cache files; defaults to "generated_data"
    """
    
    if test_start_ind <= validation_start_ind:
            raise ValueError("test_start_ind must exceed validation_start_ind")

    # Check that all NDArrays have the same length
    array_lengths = set(
        len(arr) for d in (data_to_cache, gt_to_cache) for arr in d.values()
    )
    if len(array_lengths) != 1:
        raise ValueError("All NDArrays must have the same length")

    # Check that test_start_ind does not exceed the length of the arrays
    array_length = next(iter(array_lengths))
    if test_start_ind >= array_length:
        raise ValueError("test_start_ind must not exceed data length")

    filepath = get_cache_filepath(cache_key, cache_dir)

    # We now create a new dictionary that merges `data_to_cache` with a version
    # of `gt_to_cache` that replaces each of its keys with the .name attribute
    # of the original keys
    merged_data: typing.Dict[str, ArrayLike] = {
        **data_to_cache, **{mode.name: arr for mode, arr in gt_to_cache.items()}
    }
    merged_data[CacheKeys.VALIDATION_START_IND_KEY] = validation_start_ind
    merged_data[CacheKeys.TEST_START_IND_KEY] = test_start_ind

    merged_data[CacheKeys.POS_SCALE_KEY] = np.asarray(pos_scale)
    merged_data[CacheKeys.ROT_SCALE_KEY] = np.asarray(rot_scale)

    np.savez_compressed(filepath, allow_pickle=False, **merged_data)
    print(f"Cached data saved to {filepath}")


def load_cached_data(
    cache_key: str, out_vec_mode: OutVecMode,
    pos_scale: float, rot_scale: float,
    cache_dir: str = CACHE_DATA_LOCATION
) -> typing.Optional[typing.Dict[str, typing.Dict[DataSubsetKind, NDArray]]]:
    """
    Load cached data from disk if it exists and filter by skip value.
    
    Parameters:
        cache_key (str): Unique identifier for this cache
        out_vec_mode (OutVecMode): Which OutVecMode to load ground truth for
        pos_scale (float): Scaling used for translations in the calling code
        rot_scale (float): Scaling used for rotations in the calling code
        cache_dir: Directory where cache files are stored
    
    Returns:
        Dictionary with cached data or None if cache doesn't exist
    """
    filepath = get_cache_filepath(cache_key, cache_dir)
    
    if not filepath.exists():
        return None
    
    try:
        # Load the compressed data
        data = np.load(filepath, allow_pickle=False)

        load_pos_scale = data[CacheKeys.POS_SCALE_KEY]
        load_rot_scale = data[CacheKeys.ROT_SCALE_KEY]
        scales_close = np.allclose(
            [pos_scale, rot_scale], [load_pos_scale, load_rot_scale]
        )
        if not scales_close:
            raise NotImplementedError("Scales differ! Handling that's a TODO.")
        
        load_res: typing.Dict[str, typing.Dict[DataSubsetKind, NDArray]] = {}
        for key in data.keys():
            if key in (CacheKeys.POS_SCALE_KEY, CacheKeys.ROT_SCALE_KEY):
                continue
            if key.startswith(CacheKeys.GT_STORAGE_KEY):
                continue

            # Split on last underscore to separate base name from subset kind
            parts = key.rsplit('_', 1)
            if len(parts) == 2:
                base_name, subset_name = parts
                if base_name not in load_res:
                    load_res[base_name] = typing.cast(
                        typing.Dict[DataSubsetKind, NDArray], {}
                    )
                curr_dsk = DataSubsetKind.fromName(subset_name)
                load_res[base_name][curr_dsk] = data[key]
            else:
                # Single value, not per-subset
                raise ValueError(
                    "Unexpected key without DataSubsetKind: " + repr(key)
                )
                # result[key] = data[key]
                        
        print(f"Loaded cached data from {filepath}")
        return load_res
        
    except Exception as e:
        print(f"Error loading cache: {e}")
        return None

# TODO/WIP notes:
# - https://github.com/numpy/numpy/issues/22435
