"""
Caching utilities for expensive DataForJAV computations.
Saves large NDArrays to disk and loads them on subsequent runs.

This code was initially generated by Claude Sonnet 4.5 and Cline in an attempt
to see whether they would be able to automate a task. They were able to perform
part of it but I've given up and will be finishing the rest solo. I will also
probably forget to update this comment after doing so.
"""
import hashlib
import json
import typing
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from datatools.data_splitting import DataSubsetKind
from nn_utilities.nn_modes import OutVecMode

GT_STORAGE_KEY = "gt_for_outvecmode"
CACHE_DATA_LOCATION = "generated_data"
POS_SCALE_KEY = "pos_scale"
ROT_SCALE_KEY = "rot_scale"


def gen_cache_key(
    dataset_name: str, data_ids: typing.Dict[DataSubsetKind, typing.List]
) -> str:
    """
    Generate a unique cache key based on parameters that affect the computation.
    
    Parameters:
        dataset_name (str): Name of dataset the IDs are for
        data_ids: Dictionary mapping subset kinds to lists of data IDs
    
    Returns:
        A string that uniquely identifies this configuration
    """
    # Create a dictionary of all parameters that affect computation
    cache_params = {
        'train_ids': [repr(tuple(x)) for x in data_ids[DataSubsetKind.TRAIN]],
        'test_ids': [repr(tuple(x)) for x in data_ids[DataSubsetKind.TEST]],
        'validation_ids': [repr(tuple(x)) for x in data_ids[DataSubsetKind.VALIDATION]]
    }
    
    # Convert to JSON string for hashing (sorted for consistency)
    params_str = json.dumps(cache_params, sort_keys=True)
    
    # Generate hash
    hash_obj = hashlib.sha256(params_str.encode('utf-8'))
    return dataset_name + "_" + hash_obj.hexdigest()[:16]  # 16 for brevity


def get_cache_filepath(cache_key: str, cache_dir: str = CACHE_DATA_LOCATION) -> Path:
    """Get the filepath for a cache file."""
    cache_path = Path(cache_dir)
    cache_path.mkdir(exist_ok=True)
    return cache_path / f"data_cache_{cache_key}.npz"


def save_cached_data(
    cache_key: str,
    data_to_cache: typing.Dict[str, typing.Dict[DataSubsetKind, NDArray]],
    gt_to_cache: typing.Dict[OutVecMode, typing.Dict[DataSubsetKind, NDArray]],
    pos_scale: float, rot_scale: float, cache_dir: str = CACHE_DATA_LOCATION
) -> None:
    """
    Save expensive computed arrays to disk.
    
    Parameters:
        cache_key: Unique identifier for this cache
        data_to_cache: Dictionary containing various data to cache
        gt_to_cache: Dictionary containing all ground truth data to cache
        pos_scale (float): Scaling used for translations
        rot_scale (float): Scaling used for rotations
        cache_dir: Directory to save cache files
    """
    filepath = get_cache_filepath(cache_key, cache_dir)
    
    # Build the save dictionary with flattened structure for npz
    save_dict = {}
    
    for key, dsk_dict in data_to_cache.items():
        for subset_kind, arr in dsk_dict.items():
            save_dict[f"{key}_{subset_kind.name}"] = arr
    for ovm, dsk_dict in gt_to_cache.items():
        for subset_kind, arr in dsk_dict.items():
            save_dict[f"{ovm.name}_{subset_kind.name}"] = arr

    save_dict[POS_SCALE_KEY] = np.asarray(pos_scale)
    save_dict[ROT_SCALE_KEY] = np.asarray(rot_scale)

    np.savez_compressed(filepath, **save_dict)
    print(f"Cached data saved to {filepath}")


def load_cached_data(
    cache_key: str, out_vec_mode: OutVecMode,
    pos_scale: float, rot_scale: float,
    cache_dir: str = CACHE_DATA_LOCATION
) -> typing.Optional[typing.Dict[str, typing.Dict[DataSubsetKind, NDArray]]]:
    """
    Load cached data from disk if it exists and filter by skip value.
    
    Parameters:
        cache_key (str): Unique identifier for this cache
        out_vec_mode (OutVecMode): Which OutVecMode to load ground truth for
        pos_scale (float): Scaling used for translations in the calling code
        rot_scale (float): Scaling used for rotations in the calling code
        cache_dir: Directory where cache files are stored
    
    Returns:
        Dictionary with cached data or None if cache doesn't exist
    """
    filepath = get_cache_filepath(cache_key, cache_dir)
    
    if not filepath.exists():
        return None
    
    try:
        # Load the compressed data
        data = np.load(filepath, allow_pickle=False)

        load_pos_scale = data[POS_SCALE_KEY]
        load_rot_scale = data[ROT_SCALE_KEY]
        scales_close = np.allclose(
            [pos_scale, rot_scale], [load_pos_scale, load_rot_scale]
        )
        if not scales_close:
            raise NotImplementedError("Scales differ! Handling that's a TODO.")
        
        load_res: typing.Dict[str, typing.Dict[DataSubsetKind, NDArray]] = {}
        for key in data.keys():
            if key in (POS_SCALE_KEY, ROT_SCALE_KEY):
                continue
            if key.startswith(GT_STORAGE_KEY):
                continue

            # Split on last underscore to separate base name from subset kind
            parts = key.rsplit('_', 1)
            if len(parts) == 2:
                base_name, subset_name = parts
                if base_name not in load_res:
                    load_res[base_name] = typing.cast(
                        typing.Dict[DataSubsetKind, NDArray], {}
                    )
                curr_dsk = DataSubsetKind.fromName(subset_name)
                load_res[base_name][curr_dsk] = data[key]
            else:
                # Single value, not per-subset
                raise ValueError(
                    "Unexpected key without DataSubsetKind: " + repr(key)
                )
                # result[key] = data[key]
                        
        print(f"Loaded cached data from {filepath}")
        return load_res
        
    except Exception as e:
        print(f"Error loading cache: {e}")
        return None

# TODO/WIP notes:
# - https://github.com/numpy/numpy/issues/22435
