"""
Caching utilities for expensive DataForJAV computations.
Saves large NDArrays to disk and loads them on subsequent runs.

This code was initially generated by Claude Sonnet 4.5 and Cline in an attempt
to see whether they would be able to automate a task. They were able to perform
part of it but I've given up and will be finishing the rest solo. I will also
probably forget to update this comment after doing so.
"""
import hashlib
import json
import typing
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from datatools.data_splitting import DataSubsetKind
from motiontools.dataorg import SkipSubsetKind


def generate_cache_key(
    data_ids: typing.Dict[DataSubsetKind, typing.List],
    save_data_for_conf: bool
) -> str:
    """
    Generate a unique cache key based on parameters that affect the computation.
    
    Parameters:
        data_ids: Dictionary mapping subset kinds to lists of data IDs
        save_data_for_conf: Whether confidence interval data is saved
    
    Returns:
        A hash string that uniquely identifies this configuration
    """
    # Create a dictionary of all parameters that affect computation
    cache_params = {
        'train_ids': sorted([tuple(x) for x in data_ids[DataSubsetKind.TRAIN]]),
        'test_ids': sorted([tuple(x) for x in data_ids[DataSubsetKind.TEST]]),
        'validation_ids': sorted([tuple(x) for x in data_ids[DataSubsetKind.VALIDATION]]),
        'save_data_for_conf': save_data_for_conf,
    }
    
    # Convert to JSON string for hashing (sorted for consistency)
    params_str = json.dumps(cache_params, sort_keys=True)
    
    # Generate hash
    hash_obj = hashlib.sha256(params_str.encode('utf-8'))
    return hash_obj.hexdigest()[:16]  # Use first 16 chars for brevity


def get_cache_filepath(cache_key: str, cache_dir: str = "generated_data") -> Path:
    """Get the filepath for a cache file."""
    cache_path = Path(cache_dir)
    cache_path.mkdir(exist_ok=True)
    return cache_path / f"data_cache_{cache_key}.npz"


def save_cached_data(
    cache_key: str,
    data_to_cache: typing.Dict[str, typing.Any],
    cache_dir: str = "generated_data"
) -> None:
    """
    Save expensive computed arrays to disk.
    
    Parameters:
        cache_key: Unique identifier for this cache
        data_to_cache: Dictionary containing all data to cache with appropriate keys
        cache_dir: Directory to save cache files
    """
    filepath = get_cache_filepath(cache_key, cache_dir)
    
    # Build the save dictionary with flattened structure for npz
    save_dict = {}
    
    for key, value in data_to_cache.items():
        if isinstance(value, dict):
            # If value is a dict of subset_kind -> arrays, flatten it
            for subset_kind, arr in value.items():
                if hasattr(subset_kind, 'name'):
                    save_dict[f"{key}_{subset_kind.name}"] = arr
                else:
                    save_dict[f"{key}_{subset_kind}"] = arr
        else:
            # Direct value storage
            save_dict[key] = value
    
    np.savez_compressed(filepath, **save_dict)
    print(f"Cached data saved to {filepath}")


def load_cached_data(
    cache_key: str,
    skip: typing.Union[int, SkipSubsetKind],
    subset_skip_inds: typing.Dict[DataSubsetKind, typing.Dict[SkipSubsetKind, NDArray]],
    cache_dir: str = "generated_data"
) -> typing.Optional[typing.Dict[str, typing.Any]]:
    """
    Load cached data from disk if it exists and filter by skip value.
    
    Parameters:
        cache_key: Unique identifier for this cache
        skip: Skip amount or SkipSubsetKind to filter data
        subset_skip_inds: Indices dictionary from DataOrganizer for filtering
        cache_dir: Directory where cache files are stored
    
    Returns:
        Dictionary with cached data or None if cache doesn't exist
    """
    filepath = get_cache_filepath(cache_key, cache_dir)
    
    if not filepath.exists():
        return None
    
    try:
        # Load the compressed data
        data = np.load(filepath, allow_pickle=True)
        
        # Get skip indices for filtering
        skip_val = skip if isinstance(skip, SkipSubsetKind) else SkipSubsetKind(skip)
        skip_inds = {
            k: ... if skip_val == SkipSubsetKind._all else v[skip_val]
            for k, v in subset_skip_inds.items()
        }
        
        # Reconstruct the nested structure
        result = {}
        
        # Group keys by their base name (before the subset kind suffix)
        key_groups = {}
        for key in data.keys():
            if key.startswith('_meta'):
                continue
            # Split on last underscore to separate base name from subset kind
            parts = key.rsplit('_', 1)
            if len(parts) == 2:
                base_name, subset_name = parts
                if base_name not in key_groups:
                    key_groups[base_name] = {}
                key_groups[base_name][subset_name] = key
            else:
                # Single value, not per-subset
                result[key] = data[key]
        
        # Reconstruct dictionaries with skip filtering
        for base_name, subset_keys in key_groups.items():
            result[base_name] = {}
            for subset_kind in DataSubsetKind.nonWholeValues():
                if subset_kind.name in subset_keys:
                    key = subset_keys[subset_kind.name]
                    arr = data[key]
                    result[base_name][subset_kind] = arr[skip_inds[subset_kind]]
        
        print(f"Loaded cached data from {filepath}")
        return result
        
    except Exception as e:
        print(f"Error loading cache: {e}")
        return None
